module.exports = {
  apps: [
    {
      name: 'crypto-server',
      script: 'dist/main.js',
    },
    {
      name: '5mins',
      script: 'dist/crons/5min.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '0/5 * * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: '15mins',
      script: 'dist/crons/15min.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '0/15 * * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: '30mins',
      script: 'dist/crons/30min.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '0/30 * * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: 'hourly',
      script: 'dist/crons/1hour.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '5 * * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: '2hourly',
      script: 'dist/crons/2hour.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '5 */2 * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: '4hourly',
      script: 'dist/crons/4hour.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '5 */4 * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: '6hourly',
      script: 'dist/crons/6hour.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '10 */6 * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: '12hourly',
      script: 'dist/crons/12hour.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '10 */12 * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: '1day',
      script: 'dist/crons/1day.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '15 0 * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: 'weekly',
      script: 'dist/crons/weekly.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '5 * * * 1',
      watch: false,
      autorestart: false,
    },
  ],
};
